version: "1.0"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
    image: velvetaccardia/crud-api
    ports:
      - "4000:4000"
    volumes:
      - /app

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/:/etc/prometheus/
    depends_on:
      - api

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana-data: